### ISSUE TITLE
[BUG] Invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by nguyen-dhn** [MLOpsVN/courses.mlops.vn#71]
**Mô tả bug**
- Tên bug:  ```Invalid mount config for type "bind": bind source path does not exist```
- Xảy ra ở bài [Training Pipeline](https://courses.mlops.vn/mlops-crash-course/training-pipeline/xay-dung-training-pipeline/).
- Xảy ra ở bước Trigger DAG trên Airflow UI.

**Specs**
* MacOS: Ventura 13.0 on Macbook Pro M1 2020
* Docker Desktop: 4.13.1
* Docker Compose: v2.12.1
* Commit hash: [d3ced8223a2dd0eaa7230a8d5261c3cc35dbbc9c](https://github.com/MLOpsVN/mlops-crash-course-code/commit/d3ced8223a2dd0eaa7230a8d5261c3cc35dbbc9c)

**Attachments**

Đính kèm dưới đây là log của `model_training_task`:
```
*** Reading local file: /opt/airflow/logs/dag_id=training_pipeline/run_id=manual__2022-11-05T02:10:51.793403+00:00/task_id=model_training_task/attempt=1.log
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: training_pipeline.model_training_task manual__2022-11-05T02:10:51.793403+00:00 [queued]>
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: training_pipeline.model_training_task manual__2022-11-05T02:10:51.793403+00:00 [queued]>
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): model_training_task> on 2022-11-05 02:10:51.793403+00:00
[2022-11-05, 02:11:29 UTC] {standard_task_runner.py:52} INFO - Started process 542 to run task
[2022-11-05, 02:11:29 UTC] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'training_pipeline', 'model_training_task', 'manual__2022-11-05T02:10:51.793403+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline/training_dag.py', '--cfg-path', '/tmp/tmpdsfagkoi', '--error-file', '/tmp/tmpc2914gq0']
[2022-11-05, 02:11:29 UTC] {standard_task_runner.py:80} INFO - Job 18: Subtask model_training_task
[2022-11-05, 02:11:29 UTC] {task_command.py:371} INFO - Running <TaskInstance: training_pipeline.model_training_task manual__2022-11-05T02:10:51.793403+00:00 [running]> on host 08e1f0f638e7
[2022-11-05, 02:11:29 UTC] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=training_pipeline
AIRFLOW_CTX_TASK_ID=model_training_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T02:10:51.793403+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-05T02:10:51.793403+00:00
[2022-11-05, 02:11:29 UTC] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/training_pipeline:latest
[2022-11-05, 02:11:29 UTC] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2022-11-05, 02:11:31 UTC] {docker.py:324} INFO - 2022-11-05, 02:11:31 UTC - model_training - INFO - start train_model
2022-11-05, 02:11:31 UTC - model_training - INFO - current dir: /training_pipeline/src
2022-11-05, 02:11:31 UTC - model_training - INFO - inspect_dir /training_pipeline/src
[2022-11-05, 02:11:31 UTC] {docker.py:324} INFO - 2022-11-05, 02:11:31 UTC - model_training - INFO - __pycache__
2022-11-05, 02:11:31 UTC - model_training - INFO - data_extraction.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_preparation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_evaluation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_training.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - utils.py
[2022-11-05, 02:11:31 UTC] {docker.py:324} INFO - Traceback (most recent call last):
  File "model_training.py", line 88, in <module>
    train_model()
  File "model_training.py", line 46, in train_model
    mlflow.set_experiment(config.experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 114, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 566, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 226, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 323, in get_experiment_by_name
    raise e
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 310, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 274, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 403 != 200. Response body: ''
[2022-11-05, 02:11:31 UTC] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.41/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 269, in _run_image
    return self._run_image_with_mounts(self.mounts + [tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 314, in _run_image_with_mounts
    tty=self.tty,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.41/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /host_mnt/private/tmp/airflowtmpm2xb_n49")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 400, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 278, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 329, in _run_image_with_mounts
    raise AirflowException(f'Docker container failed: {repr(result)} lines {joined_log_lines}')
airflow.exceptions.AirflowException: Docker container failed: {'Error': None, 'StatusCode': 1} lines 2022-11-05, 02:11:31 UTC - model_training - INFO - start train_model
2022-11-05, 02:11:31 UTC - model_training - INFO - current dir: /training_pipeline/src
2022-11-05, 02:11:31 UTC - model_training - INFO - inspect_dir /training_pipeline/src
2022-11-05, 02:11:31 UTC - model_training - INFO - __pycache__
2022-11-05, 02:11:31 UTC - model_training - INFO - data_extraction.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_preparation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_evaluation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_training.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - utils.py
Traceback (most recent call last):
  File "model_training.py", line 88, in <module>
    train_model()
  File "model_training.py", line 46, in train_model
    mlflow.set_experiment(config.experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 114, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 566, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 226, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 323, in get_experiment_by_name
    raise e
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 310, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 274, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 403 != 200. Response body: ''
[2022-11-05, 02:11:31 UTC] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=training_pipeline, task_id=model_training_task, execution_date=20221105T021051, start_date=20221105T021129, end_date=20221105T021131
[2022-11-05, 02:11:31 UTC] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task model_training_task (Docker container failed: {'Error': None, 'StatusCode': 1} lines 2022-11-05, 02:11:31 UTC - model_training - INFO - start train_model
2022-11-05, 02:11:31 UTC - model_training - INFO - current dir: /training_pipeline/src
2022-11-05, 02:11:31 UTC - model_training - INFO - inspect_dir /training_pipeline/src
2022-11-05, 02:11:31 UTC - model_training - INFO - __pycache__
2022-11-05, 02:11:31 UTC - model_training - INFO - data_extraction.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_preparation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - data_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_evaluation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_training.py
2022-11-05, 02:11:31 UTC - model_training - INFO - model_validation.py
2022-11-05, 02:11:31 UTC - model_training - INFO - utils.py
Traceback (most recent call last):
  File "model_training.py", line 88, in <module>
    train_model()
  File "model_training.py", line 46, in train_model
    mlflow.set_experiment(config.experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 114, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 566, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 226, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 323, in get_experiment_by_name
    raise e
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 310, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 274, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 403 != 200. Response body: ''; 542)
[2022-11-05, 02:11:31 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-05, 02:11:31 UTC] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
```
**Hướng giải quyết**
Dự đoán là lỗi đặc thù của môi trường Docker trên Mac M1. Sau khi tìm hiểu thì mình có tham khảo cách giải quyết [ở đây](https://github.com/docker/docs/issues/4709#issuecomment-639596451). 

TL;DR: Thêm Docker ở MacOS Settings » Security » Privacy » Full Disk Access. Sau đó down hết các services và up lên lại.

Tuy nhiên lỗi vẫn xảy ra. Phải chăng là mình cần config thêm `/host_mnt` trong Docker Desktop >> Preferences >> Resources >> File sharing?

**Comment by nguyen-dhn** [comment]
This issue is a side effect of issue #78. After fixing that issue, this bug has gone.
