### ISSUE TITLE
[BUG] Service `airflow-init` exited on start and warning on service `docker-proxy` when running

### ISSUE THREAD

**Issue by nguyen-dhn** [MLOpsVN/courses.mlops.vn#75]
**Mô tả bug**
- Tên bug: Container `airflow-init` bị exited khi khởi tạo and warning trên Docker Desktop từ container `docker-proxy` khi chạy.
- Xảy ra ở bước khởi tạo Airflow service từ `mlops-crash-course-platform`

**Cách tạo lại bug** (tại repo `mlops-crash-course-platform`)
- Start Airflow service: `./run.sh airflow up`

**Attachments**
1. Docker Desktop: 
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/49564851/200112278-95375e9c-1822-4138-951d-f4786f2e4e42.png">

2. Log từ `airflow-init` container:

```
[2022-11-05 08:42:24,883] {providers_manager.py:227} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.asb.BaseAzureServiceBusHook' from 'apache-airflow-providers-microsoft-azure' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/asb.py", line 19, in <module>
    from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender
ModuleNotFoundError: No module named 'azure.servicebus'
[2022-11-05 08:42:25,232] {manager.py:819} WARNING - No user yet created, use flask fab command to do it.
[2022-11-05 08:42:25,404] {providers_manager.py:218} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
[2022-11-05 08:42:25,406] {providers_manager.py:227} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.asb.BaseAzureServiceBusHook' from 'apache-airflow-providers-microsoft-azure' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/asb.py", line 19, in <module>
    from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender
ModuleNotFoundError: No module named 'azure.servicebus'
[2022-11-05 08:42:25,481] {providers_manager.py:218} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
[2022-11-05 08:42:25,482] {providers_manager.py:227} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.asb.BaseAzureServiceBusHook' from 'apache-airflow-providers-microsoft-azure' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/asb.py", line 19, in <module>
    from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender
ModuleNotFoundError: No module named 'azure.servicebus'
Upgrades done
[2022-11-05 08:42:27,365] {manager.py:819} WARNING - No user yet created, use flask fab command to do it.
[2022-11-05 08:42:27,400] {manager.py:508} INFO - Created Permission View: menu access on List Users
[2022-11-05 08:42:27,403] {manager.py:568} INFO - Added Permission menu access on List Users to role Admin
[2022-11-05 08:42:27,408] {manager.py:508} INFO - Created Permission View: menu access on Security
[2022-11-05 08:42:27,411] {manager.py:568} INFO - Added Permission menu access on Security to role Admin
[2022-11-05 08:42:27,422] {manager.py:508} INFO - Created Permission View: menu access on List Roles
[2022-11-05 08:42:27,425] {manager.py:568} INFO - Added Permission menu access on List Roles to role Admin
[2022-11-05 08:42:27,433] {manager.py:508} INFO - Created Permission View: can read on User Stats Chart
[2022-11-05 08:42:27,436] {manager.py:568} INFO - Added Permission can read on User Stats Chart to role Admin
[2022-11-05 08:42:27,440] {manager.py:508} INFO - Created Permission View: menu access on User's Statistics
[2022-11-05 08:42:27,443] {manager.py:568} INFO - Added Permission menu access on User's Statistics to role Admin
[2022-11-05 08:42:27,458] {manager.py:508} INFO - Created Permission View: menu access on Actions
[2022-11-05 08:42:27,460] {manager.py:568} INFO - Added Permission menu access on Actions to role Admin
[2022-11-05 08:42:27,471] {manager.py:508} INFO - Created Permission View: can read on View Menus
[2022-11-05 08:42:27,474] {manager.py:568} INFO - Added Permission can read on View Menus to role Admin
[2022-11-05 08:42:27,479] {manager.py:508} INFO - Created Permission View: menu access on Resources
INFO  [alembic.runtime.migration] Running upgrade 82b7c48c147f -> 449b4072c2da, Increase size of ``connection.extra`` field to handle multiple RSA keys
INFO  [alembic.runtime.migration] Running upgrade 449b4072c2da -> 8646922c8a04, Change default ``pool_slots`` to ``1``
INFO  [alembic.runtime.migration] Running upgrade 8646922c8a04 -> 2e42bb497a22, Rename ``last_scheduler_run`` column in ``DAG`` table to ``last_parsed_time``
INFO  [alembic.runtime.migration] Running upgrade 2e42bb497a22 -> 90d1635d7b86, Increase maximum length of pool name in ``task_instance`` table to ``256`` characters
INFO  [alembic.runtime.migration] Running upgrade 90d1635d7b86 -> e165e7455d70, Add description field to ``Variable`` model
INFO  [alembic.runtime.migration] Running upgrade e165e7455d70 -> a13f7613ad25, Resource based permissions for default ``Flask-AppBuilder`` views
INFO  [alembic.runtime.migration] Running upgrade a13f7613ad25 -> 97cdd93827b8, Add ``queued_at`` column in ``dag_run`` table
INFO  [alembic.runtime.migration] Running upgrade 97cdd93827b8 -> 092435bf5d12, Add ``max_active_runs`` column to ``dag_model`` table
INFO  [alembic.runtime.migration] Running upgrade 092435bf5d12 -> ccde3e26fe78, Add index on state, dag_id for queued ``dagrun``
INFO  [alembic.runtime.migration] Running upgrade ccde3e26fe78 -> 83f031fd9f1c, Improve MSSQL compatibility
INFO  [alembic.runtime.migration] Running upgrade 83f031fd9f1c -> e9304a3141f0, Make XCom primary key columns non-nullable
INFO  [alembic.runtime.migration] Running upgrade e9304a3141f0 -> 30867afad44a, Rename ``concurrency`` column in ``dag`` table to`` max_active_tasks``
INFO  [alembic.runtime.migration] Running upgrade 30867afad44a -> 54bebd308c5f, Adds ``trigger`` table and deferrable operator columns to task instance
INFO  [alembic.runtime.migration] Running upgrade 54bebd308c5f -> 142555e44c17, Add data_interval_[start|end] to DagModel and DagRun.
INFO  [alembic.runtime.migration] Running upgrade 142555e44c17 -> 7b2661a43ba3, Change ``TaskInstance`` and ``TaskReschedule`` tables from execution_date to run_id.
INFO  [alembic.runtime.migration] Running upgrade 7b2661a43ba3 -> be2bfac3da23, Add has_import_errors column to DagModel
INFO  [alembic.runtime.migration] Running upgrade be2bfac3da23 -> c381b21cb7e4, Create a ``session`` table to store web session data
INFO  [alembic.runtime.migration] Running upgrade c381b21cb7e4 -> 587bdf053233, Add index for ``dag_id`` column in ``job`` table.
INFO  [alembic.runtime.migration] Running upgrade 587bdf053233 -> 5e3ec427fdd3, Increase length of email and username in ``ab_user`` and ``ab_register_user`` table to ``256`` characters
INFO  [alembic.runtime.migration] Running upgrade 5e3ec427fdd3 -> 786e3737b18f, Add ``timetable_description`` column to DagModel for UI.
INFO  [alembic.runtime.migration] Running upgrade 786e3737b18f -> f9da662e7089, Add ``LogTemplate`` table to track changes to config values ``log_filename_template``
INFO  [alembic.runtime.migration] Running upgrade f9da662e7089 -> e655c0453f75, Add ``map_index`` column to TaskInstance to identify task-mapping,
and a ``task_map`` table to track mapping values from XCom.
INFO  [alembic.runtime.migration] Running upgrade e655c0453f75 -> a3bcd0914482, add data_compressed to serialized_dag
INFO  [alembic.runtime.migration] Running upgrade a3bcd0914482 -> c306b5b5ae4a, Switch XCom table to use ``run_id`` and add ``map_index``.
INFO  [alembic.runtime.migration] Running upgrade c306b5b5ae4a -> c97c2ab6aa23, add callback request table
INFO  [alembic.runtime.migration] Running upgrade c97c2ab6aa23 -> 4eaab2fe6582, Migrate RTIF to use run_id and map_index
INFO  [alembic.runtime.migration] Running upgrade 4eaab2fe6582 -> 48925b2719cb, Add map_index to TaskFail
INFO  [alembic.runtime.migration] Running upgrade 48925b2719cb -> 909884dea523, Update migration for FAB tables to add missing constraints
INFO  [alembic.runtime.migration] Running upgrade 909884dea523 -> 75d5ed6c2b43, Add map_index to Log.
INFO  [alembic.runtime.migration] Running upgrade 75d5ed6c2b43 -> b1b348e02d07, Update dag.default_view to grid
INFO  [alembic.runtime.migration] Running upgrade b1b348e02d07 -> 1de7bc13c950, Add index for ``event`` column in ``log`` table.
INFO  [alembic.runtime.migration] Running upgrade 1de7bc13c950 -> 3c94c427fdf6, Add cascade to dag_tag foreign key
INFO  [alembic.runtime.migration] Running upgrade 3c94c427fdf6 -> f5fcbda3e651, Add indexes for CASCADE deletes on task_instance
/home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:360: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
  FutureWarning,
/home/airflow/.local/lib/python3.7/site-packages/airflow/www/app.py:111 DeprecationWarning: 'app.json_encoder' is deprecated and will be removed in Flask 2.3. Customize 'app.json_provider_class' or 'app.json' instead.
/home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:360: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
  FutureWarning,
[2022-11-05 08:42:27,481] {manager.py:568} INFO - Added Permission menu access on Resources to role Admin
[2022-11-05 08:42:27,493] {manager.py:508} INFO - Created Permission View: can read on Permission Views
[2022-11-05 08:42:27,495] {manager.py:568} INFO - Added Permission can read on Permission Views to role Admin
[2022-11-05 08:42:27,501] {manager.py:508} INFO - Created Permission View: menu access on Permission Pairs
[2022-11-05 08:42:27,504] {manager.py:568} INFO - Added Permission menu access on Permission Pairs to role Admin
[2022-11-05 08:42:27,650] {manager.py:508} INFO - Created Permission View: clear on Task Instances
[2022-11-05 08:42:27,651] {manager.py:568} INFO - Added Permission clear on Task Instances to role Admin
[2022-11-05 08:42:27,654] {manager.py:508} INFO - Created Permission View: set failed on Task Instances
[2022-11-05 08:42:27,655] {manager.py:568} INFO - Added Permission set failed on Task Instances to role Admin
[2022-11-05 08:42:27,657] {manager.py:508} INFO - Created Permission View: set retry on Task Instances
[2022-11-05 08:42:27,658] {manager.py:568} INFO - Added Permission set retry on Task Instances to role Admin
[2022-11-05 08:42:27,661] {manager.py:508} INFO - Created Permission View: set running on Task Instances
[2022-11-05 08:42:27,662] {manager.py:568} INFO - Added Permission set running on Task Instances to role Admin
[2022-11-05 08:42:27,665] {manager.py:508} INFO - Created Permission View: set skipped on Task Instances
[2022-11-05 08:42:27,666] {manager.py:568} INFO - Added Permission set skipped on Task Instances to role Admin
[2022-11-05 08:42:27,668] {manager.py:508} INFO - Created Permission View: set success on Task Instances
[2022-11-05 08:42:27,669] {manager.py:568} INFO - Added Permission set success on Task Instances to role Admin
[2022-11-05 08:42:27,753] {manager.py:508} INFO - Created Permission View: menu access on Providers
[2022-11-05 08:42:27,754] {manager.py:568} INFO - Added Permission menu access on Providers to role Admin
[2022-11-05 08:42:27,784] {manager.py:508} INFO - Created Permission View: can create on XComs
[2022-11-05 08:42:27,786] {manager.py:568} INFO - Added Permission can create on XComs to role Admin
[2022-11-05 08:42:28,332] {providers_manager.py:218} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
[2022-11-05 08:42:28,485] {providers_manager.py:227} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.asb.BaseAzureServiceBusHook' from 'apache-airflow-providers-microsoft-azure' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/asb.py", line 19, in <module>
    from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender
ModuleNotFoundError: No module named 'azure.servicebus'
[2022-11-05 08:42:28,572] {providers_manager.py:218} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
[2022-11-05 08:42:28,573] {providers_manager.py:227} WARNING - Exception when importing 'airflow.providers.microsoft.azure.hooks.asb.BaseAzureServiceBusHook' from 'apache-airflow-providers-microsoft-azure' package
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/asb.py", line 19, in <module>
    from azure.servicebus import ServiceBusClient, ServiceBusMessage, ServiceBusSender
ModuleNotFoundError: No module named 'azure.servicebus'
[2022-11-05 08:42:29,190] {manager.py:213} INFO - Added user airflow
User "airflow" created with role "Admin"
2.3.4
```

3. Warning từ `airflow-proxy` container:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/49564851/200112384-89c813ac-f111-454b-9452-d9d921ce8558.png">

```
Image may have poor performance, or fail, if run via emulation
```

**Expected behaviors**
Các containers đều chạy không lỗi. 

**Specs**
 * MacOS: Ventura 13.0 on Macbook Pro M1 2020
* Docker Desktop: 4.13.1
* Docker Compose: v2.12.1
* Commit hash (mlops-crash-course-code): [d3ced8223a2dd0eaa7230a8d5261c3cc35dbbc9c](https://github.com/MLOpsVN/mlops-crash-course-code/commit/d3ced8223a2dd0eaa7230a8d5261c3cc35dbbc9c)
* Commit hash (mlops-crash-course-platform): [25602f81f8a0b978ff8661974909b45489f8015d](https://github.com/MLOpsVN/mlops-crash-course-platform/commit/25602f81f8a0b978ff8661974909b45489f8015d)

**Comment by dao-duc-tung** [comment]
This seems like a bug related to airflow
/close for now
